### ISSUE TITLE
Come up with a new name for this repository

### ISSUE THREAD

**Issue by lcolladotor** [LieberInstitute/smoking-nicotine-mouse#7]
Let's change the name of the repo :-)

**Comment by daianna21** [comment]
Guess we can leave it like that

**Comment by lcolladotor** [comment]
People will think that "Indirects" has something to do with smoking, but it's really about the name of the budget section that paid for some of this work.

**Comment by daianna21** [comment]
Ohhh ok, so could be something like smoking_nicotine_mouse??

Obtener Outlook para iOS<https://aka.ms/o0ukef>
________________________________
De: Leonardo Collado-Torres ***@***.***>
Enviado: Wednesday, January 24, 2024 9:54:05 PM
Para: LieberInstitute/smokingMouse_Indirects ***@***.***>
Cc: Daianna Gonzalez ***@***.***>; State change ***@***.***>
Asunto: Re: [LieberInstitute/smokingMouse_Indirects] Come up with a new name for this repository (Issue #7)


People will think that "Indirects" has something to do with smoking, but it's really about the name of the budget section that paid for some of this work.
